### PR TITLE
Adds keep alive connections and max sockets

### PR DESCRIPTION
**Pull request by ryankazokas**
This leverages the built in configs that axios exposes in their configs instead of manually trying to manage them. The only difference is  passing in the http agents to axios client. I will also verify that this works with non-node applications.

Also added the keep alive so that connections are pooled. There are other configs we can leverage if necessary, but a local test proved that this worked with internal services

### CODE REVIEW

**Comment by ryankazokas** [comment]
@rjdavis3 you were right, this is throwing an error when trying to run in a non node environment:

`Module not found: Error: Can't resolve 'http' in 'C:\Development\channelape-typescript-sdk\dist'`

**Comment by ryankazokas** [comment]
Closing pull request since we can't utilize this functionality because it's tied to node

**Comment by rjdavis3** [comment]
@ryankazokas thanks for testing it out. To make this easier, could we make the maxConcurrentConnections config optional (like it is) but when nothing is set just don't set a limit? I know that is riskier for Playbook but maybe then if we are setting the axios config for http agents unless the config is set then your PR will work for both?

**Comment by ryankazokas** [comment]
@rjdavis3 i tried that on friday as well before I closed out this pull request. At least even with NPM link i couldn't get it to not complain about the http/https imports needed. I even tried blocking them in the if with require statements because i thought I remember @mb-ca doing that before with the webapp, but i couldn't get it to work.

**Comment by rjdavis3** [comment]
Ok @ryankazokas . Last thought I have although hacky would be exposing the axios config as an optional param. Then we wouldn't need to import `http` or `https` within the `channelape-sdk` but others could pass in maxSockets by setting their own axios config.

https://www.npmjs.com/package/axios#axioscreateconfig

**Comment by ryankazokas** [comment]
Yeah, i think that would work @rjdavis3 . I can confirm locally to ensure there are no other issues, and then i can reopen this PR.

**Comment by rjdavis3** [comment]
@ryankazokas ok then that begs the question why we cannot just set `http.globalAgent.maxSockets` within our Node repos and be done with this. I know @mb-ca mentioned that this caused issues with the retry logic in the `channelape-sdk` initially which is why he opened #52 

I do not see why `http.globalAgent.maxSockets` wouldn't work here though since we are not creating a new agent anywhere within the repo.

**Comment by ryankazokas** [comment]
I thought about that as well, but i wasn't sure if there was a reason we were forcing the axios version of handling that. We can hold until we meet today then to discuss with @mb-ca to ensure there isn't some unknown tribal knowledge he's learned.

**Comment by mb-ca** [comment]
@rjdavis3 @ryankazokas The reason we couldn't just set `http.globalAgent.maxSockets` was because the retry timer starts right before the request is made.  This meant when node was delaying requests when it hit the `maxSockets` count, the retry timer was still running for those delayed requests and then timing out to the `maximumRequestRetryTimeout` value.

**Pull request closed without merging**
